#!/bin/sh

cd ~

echo "Make temp directory"
mkdir ~/temp

echo "Install Play 1.2.5"
wget http://download.playframework.org/releases/play-1.2.5.zip
unzip -q play-1.2.5.zip

echo "Use DotCloud version of application.conf"
cd ~/code/
cp ~/code/conf/application.conf.dotcloud ~/code/conf/application.conf

echo "Apply and play database evolutions"
../play-1.2.5/play evolutions:apply

echo "Deploy the war to temp"
../play-1.2.5/play war -o ../temp/gtfs --zip

echo "Copy war to webapps"
mv ~/temp/gtfs* ~/webapps/